import 'package:demoai/core/config/app_config.dart';
import 'package:demoai/core/config/environment_manager.dart';
import 'package:demoai/core/l10n/locale_cubit.dart';
import 'package:demoai/core/network/dio_client.dart';
import 'package:demoai/core/observers/app_bloc_observer.dart';
import 'package:demoai/core/services/env_loader_service.dart';
import 'package:demoai/core/theme/theme_cubit.dart';
import 'package:dio/dio.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart' hide Environment;
import 'package:logger/logger.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'injection_container.config.dart';

/// Service locator instance
final getIt = GetIt.instance;

/// Initialize dependency injection
Future<void> initializeDependencies({Environment? initialEnvironment}) async {
  // External dependencies
  final sharedPreferences = await SharedPreferences.getInstance();
  getIt.registerSingleton<SharedPreferences>(sharedPreferences);

  // Services
  getIt.registerLazySingleton(() => EnvLoaderService());

  // Environment Manager
  final envManager = EnvironmentManager(sharedPreferences);

  // Si se provee un ambiente inicial, usarlo (para debug)
  if (initialEnvironment != null) {
    await envManager.setEnvironment(initialEnvironment);
  }

  getIt.registerSingleton<EnvironmentManager>(envManager);

  // Load initial environment configuration
  final envLoader = getIt<EnvLoaderService>();
  final envVars = await envLoader.loadEnvFile(
    envManager.currentEnvironment.envFilePath,
  );

  // Core
  getIt.registerSingleton<AppConfig>(AppConfig.fromEnvMap(envVars));
  getIt.registerSingleton<Logger>(
    Logger(
      printer: PrettyPrinter(
        methodCount: 0,
        errorMethodCount: 5,
        lineLength: 50,
      ),
    ),
  );
  getIt.registerSingleton<AppBlocObserver>(AppBlocObserver(getIt<Logger>()));

  // Network
  getIt.registerLazySingleton<DioClient>(() => DioClient(getIt<AppConfig>()));
  getIt.registerLazySingleton<Dio>(() => getIt<DioClient>().dio);

  // Theme
  getIt.registerLazySingleton<ThemeCubit>(
    () => ThemeCubit(getIt<SharedPreferences>()),
  );

  // Locale/Language
  getIt.registerLazySingleton<LocaleCubit>(
    () => LocaleCubit(getIt<SharedPreferences>()),
  );

  // Use code generation to register injectable annotated classes
  getIt.init();

  // Rest of injections are generated by injectable

  // Demo Feature
  // Demo feature registrations are also provided by the generated config
}

@InjectableInit()
Future<void> configureGeneratedDependencies() async => getIt.init();

/// Reload dependencies when environment changes
Future<void> reloadDependenciesForEnvironment() async {
  final envLoader = getIt<EnvLoaderService>();
  final envManager = getIt<EnvironmentManager>();

  final envVars = await envLoader.loadEnvFile(
    envManager.currentEnvironment.envFilePath,
  );

  await getIt.unregister<AppConfig>();
  getIt.registerSingleton<AppConfig>(AppConfig.fromEnvMap(envVars));

  if (getIt.isRegistered<DioClient>()) {
    await getIt.unregister<DioClient>();
    getIt.registerLazySingleton<DioClient>(() => DioClient(getIt<AppConfig>()));
  }

  if (getIt.isRegistered<Dio>()) {
    await getIt.unregister<Dio>();
    getIt.registerLazySingleton<Dio>(() => getIt<DioClient>().dio);
  }

  // Demo feature uses injectable generated configuration - no manual re-registration
}
